### ISSUE TITLE
pipec and privileges

### ISSUE THREAD

**Issue by dolanor** [cncd/pipeline#13]
Hi,
I tried to use pipec to add network aliases to it.
My config
```yaml
workspace:
  base: /workspace
  path: src

pipeline:
  test-app:
    image: test/image
    commands:
      - ./ci/setup.sh
      - ./ci/test.sh
    privileged: true
    networks:
      default:
        aliases:
          - api.test-app
          - intranet.test-app

```
Launching a `pipec lint` on it return a:
```
Insufficient privileges to use privileged mode
```
