### ISSUE TITLE
Enabled cache

### ISSUE THREAD

**Issue by bugbuilder** [cncd/pipeline#23]
Hi!

I'm thinking how to acomplish this and at this moment I've coded something like this:

**drone-volume-cache**
 ```
 cache:
   type: local
   mount:
     - node_modules
     - .m2
```
**drone-s3-cache**
 ```
 cache:
   type: s3
   mount:
     - node_modules
     - .m2
   settings:
    - path=my-bucket
   secrets: [ cache_s3_access_key, cache_s3_key ]
```
But I feel that this doesn't look familiar, for this reason I'm thinking to code something like this:
**drone-volume-cache**
 ```
 cache:
   image: plugins/volume-cache
   mount:
     - node_modules
     - .m2
```

**drone-s3-cache**
 ```
 cache:
   image: plugins/drone-s3-cache
   mount:
     - node_modules
     - .m2
  path: my-bucket
  secrets: [ cache_s3_access_key, cache_s3_key ]
```
But before starting I'll welcome feedback.
