### ISSUE TITLE
Implement a Pipeline and BuildAgent Kubernetes operator 

### ISSUE THREAD

**Issue by aleccunningham** [cncd/pipeline#38]
Now that extending the Kubernetes API with CRD's is pretty simple, I think it's worth looking at possibly creating a Pipeline operator.

## CustomResourceDefinitions
CRD's are kubernetes native resources, like `Deployment`, `Service` and the like. My proposal includes the creation of two new resources, `Pipeline` and `BuildAgent`. A `Pipeline` resource would look very similar to a `.drone.yaml` file.
In contrast, a `BuildAgent` resource defines a "pipeline runner".  The `pipeline-operator` would spawn `BuildAgent`'s defined from a `BuildAgent` manifest on certain event triggers defined in the `Pipeline` resource. 
With the introduction of these two resources, a helm chart would have the following manifests for an example web application:
- `Deployment`
- `Pipeline`
- `BuildAgent`
- `Service`
- `ConfigMap, Secrets`

The `Pipeline` resource would use a `selector` spec to specify which `Deployment` corresponds with the `Pipeline`. In theory, the steps defined in the `Pipeline` would be ran on certain triggers defined in the `Pipeline` via a `BuildWorker`, created by the `pipeline-operator`.

Example `pipeline.yaml`:
```yaml
apiVersion: pipeline.duke.lol/v1alpha1
kind: Pipeline
metadata:
  name: project-pipeline
  labels:
    operator: pipeline-operator
spec:
  selector:
    app: sample-app
    group: sample-group
  sourceRepository: github.com:marjoram/pipeline.git
  dockerfile: Dockerfile.pipeline
  ssh:
    hostPath: /tmp/.ssh/id_rsa
  steps:
    - name: test
      image: golang:1.9
      commands:
        - go get ./...
        - go test
      env:
        - GOPATH=/workspace/go
      volumeMount:
        - name: test-scripts
          hostPath: /workspace/scripts
  volumes:
    - name: test-scripts
      hostPath: /workspace/scripts
  notify:
    when:
      event: ["on_success", "on_failure"]
    where:
      slack:
        channel:
          - general
          - example
        token:
          - name: slack-token
            secretFrom: /workspace/config
      email:
        from_address: technology@company.com
        to_address:
          - dev1@gmail.com
          - dev2@gmail.com
  when:
    event: ["on_commit", "on_pr"]
    branch: master
  worker:
    replicas:
      minReplicas: 1
      maxReplicas: 4
    resources:
      requests:
        cpu:
        memory:
      limits:
        cpu: 
        memory:
```
The operator would be deployed via a `Deployment`:
```yaml
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: pipeline-operator
  name: pipeline-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pipeline-operator
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: pipeline-operator
    spec:
      containers:
      - image: quay.io/marjoram/pipeline-operator:0.1.0
        imagePullPolicy: IfNotPresent
        name: app
        resources:
          limits:
            cpu: 100m
            memory: 50Mi
          requests:
            cpu: 10m
            memory: 50Mi
         restartPolicy: Always
```
You can see an example `Pipeline` type definition in the current operator repo https://github.com/marjoram/pipeline-operator/

The api `types` are defined here: https://github.com/marjoram/pipeline-operator/blob/master/apis/pipeline.duke.lol/v1alpha1/types.go

This is super high level and just a start, but it would be a step in the right direction, especially from the angle of cncd.
